/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HostWithUsRouteImport } from './routes/host-with-us'
import { Route as ExperienceSlugRouteImport } from './routes/experience.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrderConfirmationOrderRefRouteImport } from './routes/order.confirmation.$orderRef'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HostWithUsRoute = HostWithUsRouteImport.update({
  id: '/host-with-us',
  path: '/host-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceSlugRoute = ExperienceSlugRouteImport.update({
  id: '/experience/$slug',
  path: '/experience/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationOrderRefRoute =
  OrderConfirmationOrderRefRouteImport.update({
    id: '/order/confirmation/$orderRef',
    path: '/order/confirmation/$orderRef',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/host-with-us': typeof HostWithUsRoute
  '/experience/$slug': typeof ExperienceSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/order/confirmation/$orderRef': typeof OrderConfirmationOrderRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/host-with-us': typeof HostWithUsRoute
  '/experience/$slug': typeof ExperienceSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/order/confirmation/$orderRef': typeof OrderConfirmationOrderRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/host-with-us': typeof HostWithUsRoute
  '/experience/$slug': typeof ExperienceSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/order/confirmation/$orderRef': typeof OrderConfirmationOrderRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/host-with-us'
    | '/experience/$slug'
    | '/product/$slug'
    | '/order/confirmation/$orderRef'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/host-with-us'
    | '/experience/$slug'
    | '/product/$slug'
    | '/order/confirmation/$orderRef'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/host-with-us'
    | '/experience/$slug'
    | '/product/$slug'
    | '/order/confirmation/$orderRef'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HostWithUsRoute: typeof HostWithUsRoute
  ExperienceSlugRoute: typeof ExperienceSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  OrderConfirmationOrderRefRoute: typeof OrderConfirmationOrderRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-with-us': {
      id: '/host-with-us'
      path: '/host-with-us'
      fullPath: '/host-with-us'
      preLoaderRoute: typeof HostWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/$slug': {
      id: '/experience/$slug'
      path: '/experience/$slug'
      fullPath: '/experience/$slug'
      preLoaderRoute: typeof ExperienceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/confirmation/$orderRef': {
      id: '/order/confirmation/$orderRef'
      path: '/order/confirmation/$orderRef'
      fullPath: '/order/confirmation/$orderRef'
      preLoaderRoute: typeof OrderConfirmationOrderRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HostWithUsRoute: HostWithUsRoute,
  ExperienceSlugRoute: ExperienceSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  OrderConfirmationOrderRefRoute: OrderConfirmationOrderRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
